# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N9tL-Gy-178qDuUZKMn8WTXlFUe90fVY
"""

!pip install torch_geometric

"""# Environment Setup & Graph Generation #"""

# =====================================================================
# SECTIONS 1 & 2: Data Ingestion and Normalization (LA Deployment)
# =====================================================================
!pip install -q torch_geometric
from huggingface_hub import hf_hub_download
import pandas as pd
import numpy as np
import pickle
import torch
from torch.utils.data import Dataset, DataLoader
import os

print("Fetching LA dataset and building tensors...")

# 1. Download Data
h5_path = hf_hub_download(repo_id="MintBruce/SkyTraffic", filename="metr-la.h5", repo_type="dataset")
!wget -q -O adj_mx.pkl "https://raw.githubusercontent.com/liyaguang/DCRNN/master/data/sensor_graph/adj_mx.pkl"

# 2. Extract Data
df = pd.read_hdf(h5_path)
with open("adj_mx.pkl", 'rb') as f:
    _, _, adj_mx = pickle.load(f, encoding='latin1')

# 3. Format Tensors
traffic_data = torch.tensor(df.values, dtype=torch.float32).unsqueeze(-1)
edges = np.where(adj_mx > 0)
edge_index = torch.tensor(np.vstack(edges), dtype=torch.long)

# 4. Normalize (Z-Score)
split_idx = int(traffic_data.shape[0] * 0.7)
val_idx = int(traffic_data.shape[0] * 0.8)
mean = traffic_data[:split_idx].mean()
std = traffic_data[:split_idx].std()
traffic_data_norm = (traffic_data - mean) / std

# 5. Define Sliding Window Dataset
class TrafficDataset(Dataset):
    def __init__(self, data, seq_len_in, seq_len_out):
        self.data = data
        self.seq_len_in = seq_len_in
        self.seq_len_out = seq_len_out

    def __len__(self):
        return len(self.data) - self.seq_len_in - self.seq_len_out + 1

    def __getitem__(self, idx):
        x = self.data[idx : idx + self.seq_len_in]
        y = self.data[idx + self.seq_len_in : idx + self.seq_len_in + self.seq_len_out]
        return x, y.squeeze(-1)

# 6. Initialize DataLoaders
seq_in, seq_out, batch_size = 12, 3, 64

train_loader = DataLoader(TrafficDataset(traffic_data_norm[:split_idx], seq_in, seq_out), batch_size=batch_size, shuffle=True)
val_loader = DataLoader(TrafficDataset(traffic_data_norm[split_idx:val_idx], seq_in, seq_out), batch_size=batch_size, shuffle=False)
test_loader = DataLoader(TrafficDataset(traffic_data_norm[val_idx:], seq_in, seq_out), batch_size=batch_size, shuffle=False)

sample_x, sample_y = next(iter(train_loader))
print(f"✅ Data Ready! X Shape: {list(sample_x.shape)} | Y Shape: {list(sample_y.shape)}")

"""# The Ensemble Architecture (STGNN) #"""

# =====================================================================
# STEP 3.1: Define the Upgraded GAT + LSTM Architecture (FIXED)
# =====================================================================
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GATConv

class TrafficGAT_LSTM(nn.Module):
    def __init__(self, in_channels, hidden_dim, seq_len_out, num_heads=4):
        super(TrafficGAT_LSTM, self).__init__()
        self.seq_len_out = seq_len_out

        # 1. SPATIAL LAYER: Graph Attention Network (GAT)
        self.gat = GATConv(in_channels, hidden_dim // num_heads, heads=num_heads, concat=True)

        # 2. TEMPORAL LAYER: LSTM
        self.lstm = nn.LSTM(input_size=hidden_dim, hidden_size=hidden_dim, batch_first=True)

        # 3. REGRESSION HEAD: Output Predictions
        self.regressor = nn.Linear(hidden_dim, seq_len_out)

    def forward(self, x, edge_index):
        # x shape: [Batch, Time, Nodes, Features]
        batch_size, seq_len, num_nodes, num_features = x.size()

        # --- THE FIX: Create a 2D Batched Edge Index ---
        # Flatten the batch of graphs into one giant disconnected 2D graph
        # so GATConv can calculate attention without crashing.
        batched_edges = []
        for i in range(batch_size):
            offset = i * num_nodes
            batched_edges.append(edge_index + offset)
        batched_edge_index = torch.cat(batched_edges, dim=1)

        # --- PHASE 1: Dynamic Spatial Attention (GAT) ---
        gat_out = []
        for t in range(seq_len):
            x_t = x[:, t, :, :] # Extract time step: [Batch, Nodes, Features]

            # Flatten Batch and Nodes into 2D: [Batch * Nodes, Features]
            x_t_flat = x_t.reshape(batch_size * num_nodes, num_features)

            # Push through GAT
            out_t = self.gat(x_t_flat, batched_edge_index)
            out_t = F.relu(out_t)

            # Fold back into 3D: [Batch, Nodes, Hidden_Dim]
            out_t = out_t.view(batch_size, num_nodes, -1)
            gat_out.append(out_t)

        gat_out = torch.stack(gat_out, dim=1)

        # --- PHASE 2: Temporal Processing (LSTM) ---
        lstm_in = gat_out.view(batch_size * num_nodes, seq_len, -1)
        lstm_out, _ = self.lstm(lstm_in)
        last_hidden_state = lstm_out[:, -1, :]

        # --- PHASE 3: Regression ---
        predictions = self.regressor(last_hidden_state)
        predictions = predictions.view(batch_size, num_nodes, self.seq_len_out)
        predictions = predictions.permute(0, 2, 1)

        return predictions

# =====================================================================
# STEP 3.2: Initialize the Architecture
# =====================================================================
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
edge_index = edge_index.to(device)

model = TrafficGAT_LSTM(in_channels=1, hidden_dim=64, seq_len_out=seq_out, num_heads=4).to(device)
print(f"✅ GAT Architecture initialized on: {device}")

sample_x = sample_x.to(device)
with torch.no_grad():
    dummy_prediction = model(sample_x, edge_index)

print(f"Target Output Shape: {list(sample_y.shape)}")
print(f"Model Prediction Shape: {list(dummy_prediction.shape)}")

"""# The Training and Validation Loop #"""

# =====================================================================
# STEP 4.1: Setup Optimizer and Loss Function
# =====================================================================
import torch.optim as optim
import time

# Mean Squared Error is the standard for regression (predicting continuous numbers)
criterion = nn.MSELoss()

# The Adam optimizer is excellent at navigating the complex gradients of LSTMs
# A learning rate of 0.001 is a safe, stable starting point
optimizer = optim.Adam(model.parameters(), lr=0.001)

# =====================================================================
# STEP 4.2: Execute the Training Loop
# =====================================================================
# We will do 10 passes over the entire dataset to verify the network is learning
num_epochs = 10

print(f"Igniting the Engine on {device}...\n")

for epoch in range(num_epochs):
    start_time = time.time()

    # --- PHASE 1: TRAINING ---
    model.train()
    train_loss = 0.0

    for batch_x, batch_y in train_loader:
        # Move the data batches to the GPU
        batch_x = batch_x.to(device)
        batch_y = batch_y.to(device)

        # 1. Forward Pass: Push data through GCN -> LSTM -> Linear layers
        predictions = model(batch_x, edge_index)

        # 2. Calculate Loss: How far off were the traffic predictions?
        loss = criterion(predictions, batch_y)

        # 3. Backward Pass: Clear old math, calculate the new gradients
        optimizer.zero_grad()
        loss.backward()

        # 4. Update Weights: Nudge the network to be slightly more accurate
        optimizer.step()

        train_loss += loss.item()

    avg_train_loss = train_loss / len(train_loader)

    # --- PHASE 2: VALIDATION ---
    # We test on unseen data to ensure the model isn't just memorizing the training set
    model.eval()
    val_loss = 0.0

    with torch.no_grad(): # Turn off gradient tracking to save memory and speed up testing
        for batch_x, batch_y in val_loader:
            batch_x = batch_x.to(device)
            batch_y = batch_y.to(device)

            predictions = model(batch_x, edge_index)
            loss = criterion(predictions, batch_y)
            val_loss += loss.item()

    avg_val_loss = val_loss / len(val_loader)
    epoch_time = time.time() - start_time

    print(f"Epoch [{epoch+1:02d}/{num_epochs}] | Time: {epoch_time:.1f}s | Train Loss: {avg_train_loss:.4f} | Val Loss: {avg_val_loss:.4f}")

print("\n✅ Initial Training Complete!")
print("If the Validation Loss went down, the ensemble is officially learning traffic patterns.")

"""# INFERENCE, SECURITY PROTOCOLS, AND HARDWARE ACTUATION #"""

# =====================================================================
# SECTION 5: INFERENCE, SECURITY PROTOCOLS, AND HARDWARE ACTUATION
# =====================================================================
import torch
import torch.nn as nn
import numpy as np
import time

# Freeze the model weights for real-time application deployment
model.eval()

# ---------------------------------------------------------------------
# STEP 5.1: Live Telemetry Streams (Automated Inputs)
# ---------------------------------------------------------------------
# In your live deployment, these dictionaries will be continuously overwritten
# by your camera loops (OpenCV/YOLO) and your microchip serial data.

live_camera_telemetry = {
    "yolo_detected_class": "car",
    "vision_blurriness_percentage": 55.0,  # Automated: Lens blur calculated via Laplacian variance
    "average_detection_confidence": 0.42   # Automated: Drops when rain blocks the view
}

live_hardware_telemetry = {
    "rain_sensor_analog_value": 750,       # Automated: ADC value from physical rain sensor (0-1023)
    "strobe_frequency_hz": 12,             # Automated: Pulse frequency counter from optical receiver
    "side_street_wait_seconds": 45         # Automated: Time tracked since lane occupancy loop triggered
}

current_military_hour = 14                 # System clock time tracking

print("--- Polling Live Sensor Array & Security Peripherals ---")

# ---------------------------------------------------------------------
# STEP 5.2: Run AI Traffic Prediction (Spatio-Temporal Inference)
# ---------------------------------------------------------------------
sample_x, sample_y_true = next(iter(test_loader))
sample_x = sample_x.to(device)

with torch.no_grad():
    predicted_y_norm = model(sample_x, edge_index)

# Un-normalize the output tensor back into physical speeds (mph)
predicted_speeds = (predicted_y_norm.cpu() * std) + mean

# Isolate the targeted intersection point (Node 0) for the next 15 minutes
node_0_prediction = predicted_speeds[0, :, 0]
average_future_speed = node_0_prediction.mean().item()
print(f"AI Projected Traffic Speed for Intersection 0: {average_future_speed:.1f} mph")

# ---------------------------------------------------------------------
# STEP 5.3: Automated Environment & Security Evaluation Engines
# ---------------------------------------------------------------------
def evaluate_environmental_hazards(camera_data, hardware_data):
    """
    Automatically calculates if adverse weather is disrupting the system.
    Triggers true if physical rain sensor spikes OR vision degradation exceeds 50%.
    """
    # High analog value means water is bridging the traces on the rain sensor
    PHYSICAL_RAIN_DETECTED = hardware_data["rain_sensor_analog_value"] > 600

    # Blurry lens or low confidence indicates visual obstruction
    VISION_OBSTRUCTED = (camera_data["vision_blurriness_percentage"] > 50.0 or
                         camera_data["average_detection_confidence"] < 0.50)

    if PHYSICAL_RAIN_DETECTED or VISION_OBSTRUCTED:
        return True
    return False

def verify_preemption_security(camera_data, hardware_data):
    """
    Blocks preemption spoofing attacks using automated multi-factor validation.
    """
    strobe_freq = hardware_data["strobe_frequency_hz"]
    detected_class = camera_data["yolo_detected_class"]

    STROBE_VALID = (10 <= strobe_freq <= 14)
    VEHICLE_VALID = (detected_class in ['ambulance', 'fire_truck', 'police_car'])

    if STROBE_VALID and VEHICLE_VALID:
        return "SECURE_EMERGENCY_OVERRIDE"
    elif STROBE_VALID and not VEHICLE_VALID:
        return "SPOOF_ATTEMPT_DETECTED"
    return "STANDARD_FLOW"

# Run automated assessments
is_environment_hazardous = evaluate_environmental_hazards(live_camera_telemetry, live_hardware_telemetry)
security_status = verify_preemption_security(live_camera_telemetry, live_hardware_telemetry)

# ---------------------------------------------------------------------
# STEP 5.4: Control Loop State Machine (Overrides & Constraints)
# ---------------------------------------------------------------------
base_green_time = 30
final_command = "HOLD_CURRENT_STATE"

# The decision tree executes rules sequentially based on safety priority
if security_status == "SPOOF_ATTEMPT_DETECTED":
    print("⚠️ SECURITY ALERT: Unauthorized preemption strobe detected! Malicious beacon ignored.")
    added_time = max(0, (40 - average_future_speed) * 1.5)
    dynamic_green_time = int(base_green_time + added_time)
    final_command = f"G:{dynamic_green_time}\n"

elif security_status == "SECURE_EMERGENCY_OVERRIDE":
    print("🚨 EMERGENCY VERIFIED: Optical and Visual signatures match. Clearing emergency path.")
    final_command = "EMERGENCY_PREEMPTION_ON\n"

elif is_environment_hazardous:
    print("🌧️ AUTOMATED SAFETY FALLBACK: Heavy rain or lens blur > 50% detected. Activating Wet Road Profile.")
    # Forces the hardware into a safe, predictable cycle with extended yellow timings
    final_command = "WET_CYCLE_60_Y6\n"

elif current_military_hour >= 13 and current_military_hour <= 15 and average_future_speed > 52:
    print("☀️ ENVIRONMENT ALERT: Peak afternoon lull with clear roads. Dropping signal into sleep mode.")
    final_command = "FLASH_YELLOW\n"

elif live_hardware_telemetry["side_street_wait_seconds"] >= 120:
    print("🛑 STARVATION OVERRIDE: Side street vehicle limit breached. Overriding grid focus to flush lane.")
    final_command = "FLUSH_SIDE_STREET\n"

else:
    print("🤖 AI OPTIMIZATION LOGIC ACTIVE: Distributing green split via Graph Attention maps.")
    added_time = max(0, (40 - average_future_speed) * 1.5)
    dynamic_green_time = int(base_green_time + added_time)

    # Anti-Flicker constraint
    MIN_GREEN_LOCK = 15
    if dynamic_green_time < MIN_GREEN_LOCK:
        dynamic_green_time = MIN_GREEN_LOCK

    final_command = f"G:{dynamic_green_time}\n"

# ---------------------------------------------------------------------
# STEP 5.5: Frame Packet Serialization
# ---------------------------------------------------------------------
print("\n--- Local System Handoff Payload ---")
print(f"Target Machine Local Port: /dev/ttyUSB0 (ESP32-S3)")
print(f"Transmitting Command String: {final_command.strip()}")